apiVersion: v1
kind: Namespace
metadata:
  name: contour
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: contour
  namespace: contour
spec:
  interval: 15m0s
  url: https://projectcontour.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: contour
  namespace: contour
spec:
  interval: 15m0s
  timeout: 5m0s
  chart:
    spec:
      chart: contour
      version: 0.7.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: contour
  releaseName: contour
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  valuesFrom: # you must override these on a per-cluster basis
    - kind: ConfigMap
      name: values
  values:
    envoy:
      resourcesPreset: large
      service:
        ipFamilyPolicy: PreferDualStack
