apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool-1
spec:
  blocks:
    - start: 169.229.226.81
      stop: 169.229.226.89
    - start: 2607:f140:8801::1:81
      stop: 2607:f140:8801::1:89
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy-1
spec:
  loadBalancerIPs: true
