apiVersion: v1
kind: ConfigMap
metadata:
  name: values
  namespace: cilium
  labels:
    reconcile.fluxcd.io/watch: Enabled
data:
  values.yaml: |
    k8sServiceHost: dna.ocf.berkeley.edu
    ingressController:
      service:
        annotations:
          lbipam.cilium.io/ips: "169.229.226.81,2607:f140:8801::1:81"
