apiVersion: v1
kind: Namespace
metadata:
  name: rook
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rook
  namespace: rook
spec:
  interval: 15m0s
  url: https://charts.rook.io/release
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook
  namespace: rook
spec:
  chart:
    spec:
      chart: rook-ceph
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rook
      version: v1.19.5
  install:
    remediation:
      retries: 3
  interval: 15m0s
  releaseName: rook
  test:
    enable: true
  timeout: 5m0s
  upgrade:
    remediation:
      retries: 3
  values:
    csi:
      csiCephFSPluginVolume:
        - hostPath:
            path: /run/booted-system/kernel-modules/lib/modules/
          name: lib-modules
        - hostPath:
            path: /nix
          name: host-nix
      csiCephFSPluginVolumeMount:
        - mountPath: /nix
          name: host-nix
          readOnly: true
      csiRBDPluginVolume:
        - hostPath:
            path: /run/booted-system/kernel-modules/lib/modules/
          name: lib-modules
        - hostPath:
            path: /nix
          name: host-nix
      csiRBDPluginVolumeMount:
        - mountPath: /nix
          name: host-nix
          readOnly: true
    dashboard:
      enabled: true
    enableDiscoveryDaemon: true
    network:
      dualStack: true
