apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cephfs-ssd
parameters:
  clusterID: rook
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook
  fsName: cephfs
  pool: cephfs-ssd
provisioner: rook.cephfs.csi.ceph.com
reclaimPolicy: Delete
