apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: imprint
  namespace: imprint
spec:
  interval: 1m0s
  ref:
    branch: main
  url: ssh://git@github.com/ocf/imprint
  secretRef:
    name: imprint-deploy-key
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: imprint-sites
  namespace: imprint
spec:
  interval: 1m0s
  ref:
    branch: main
  url: ssh://git@github.com/ocf/imprint-sites
  secretRef:
    name: imprint-sites-deploy-key
