apiVersion: v1
kind: Service
metadata:
  name: labmap2-backend
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    ocf.berkeley.edu/flux: labmap-backend
---
apiVersion: v1
kind: Service
metadata:
  name: labmap2-frontend
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    ocf.berkeley.edu/flux: labmap-frontend
