apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    ingress.kubernetes.io/force-ssl-redirect: 'true'
    io.cilium/websocket: enabled
    kubernetes.io/tls-acme: 'true'
    projectcontour.io/websocket-routes: /api
  name: labmap2-backend
spec:
  ingressClassName: contour
  rules:
  - host: labmap.ocf.berkeley.edu
    http:
      paths:
      - backend:
          service:
            name: labmap2-backend
            port:
              number: 80
        path: /api
        pathType: Prefix
  tls:
  - hosts:
    - labmap.ocf.berkeley.edu
    secretName: labmap2-backend-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    ingress.kubernetes.io/force-ssl-redirect: 'true'
    io.cilium/websocket: enabled
    kubernetes.io/tls-acme: 'true'
    projectcontour.io/websocket-routes: /
  name: labmap2-frontend
spec:
  ingressClassName: contour
  rules:
  - host: labmap.ocf.berkeley.edu
    http:
      paths:
      - backend:
          service:
            name: labmap2-frontend
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - labmap.ocf.berkeley.edu
    secretName: labmap2-frontend-tls
