apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: ceph
  namespace: rook
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v20.2.1
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  mon:
    allowMultiplePerNode: false
    count: 3
  storage:
    nodes:
      - devices:
          - config:
              deviceClass: nvme
            name: /dev/disk/by-path/pci-0000:02:00.0-nvme-1
          - config:
              deviceClass: nvme
            name: /dev/disk/by-path/pci-0000:41:00.0-nvme-1
          - config:
              deviceClass: hdd
            name: /dev/disk/by-path/pci-0000:84:00.0-ata-2
          - config:
              deviceClass: hdd
            name: /dev/disk/by-path/pci-0000:84:00.0-ata-3
        name: adenine
      - devices:
          - config:
              deviceClass: nvme
            name: /dev/disk/by-path/pci-0000:02:00.0-nvme-1
          - config:
              deviceClass: nvme
            name: /dev/disk/by-path/pci-0000:41:00.0-nvme-1
          - config:
              deviceClass: hdd
            name: /dev/disk/by-path/pci-0000:84:00.0-ata-2
          - config:
              deviceClass: hdd
            name: /dev/disk/by-path/pci-0000:84:00.0-ata-3
        name: guanine
      - devices:
          - config:
              deviceClass: nvme
            name: /dev/disk/by-path/pci-0000:02:00.0-nvme-1
          - config:
              deviceClass: nvme
            name: /dev/disk/by-path/pci-0000:41:00.0-nvme-1
          - config:
              deviceClass: hdd
            name: /dev/disk/by-path/pci-0000:84:00.0-ata-2
          - config:
              deviceClass: hdd
            name: /dev/disk/by-path/pci-0000:84:00.0-ata-3
        name: cytosine
      - devices:
          - config:
              deviceClass: nvme
            name: /dev/disk/by-path/pci-0000:02:00.0-nvme-1
          - config:
              deviceClass: nvme
            name: /dev/disk/by-path/pci-0000:41:00.0-nvme-1
          - config:
              deviceClass: hdd
            name: /dev/disk/by-path/pci-0000:84:00.0-ata-2
          - config:
              deviceClass: hdd
            name: /dev/disk/by-path/pci-0000:84:00.0-ata-3
        name: thymine
    useAllDevices: false
    useAllNodes: false
