apiVersion: v1
kind: Namespace
metadata:
  name: rook
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rook
  namespace: rook
spec:
  interval: 10m0s
  url: https://charts.rook.io/release
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook
  namespace: rook
spec:
  chart:
    spec:
      chart: rook-ceph
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rook
      version: v1.19.5
  interval: 10m0s
  timeout: 5m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  values:
    csi:
      csiCephFSPluginVolume:
      - hostPath:
          path: /run/booted-system/kernel-modules/lib/modules/
        name: lib-modules
      - hostPath:
          path: /nix
        name: host-nix
      csiCephFSPluginVolumeMount:
      - mountPath: /nix
        name: host-nix
        readOnly: true
      csiRBDPluginVolume:
      - hostPath:
          path: /run/booted-system/kernel-modules/lib/modules/
        name: lib-modules
      - hostPath:
          path: /nix
        name: host-nix
      csiRBDPluginVolumeMount:
      - mountPath: /nix
        name: host-nix
        readOnly: true
    dashboard:
      enabled: true
    enableDiscoveryDaemon: true
    network:
      dualStack: true
