apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: temp-staging
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: ssh://git@github.com/ocf/staging
  secretRef:
    name: staging-deploy-key
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: temp-staging
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./ks
  prune: true
  sourceRef:
    kind: GitRepository
    name: temp-staging
