apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-1
  namespace: metallb
spec:
  addresses:
  - "169.229.226.105-169.229.226.107"
  - "2607:f140:8801::1:105-2607:f140:8801::1:107"
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: pool-1
  namespace: metallb
spec:
  ipAddressPools:
  - pool-1
