apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden
    namespace: vaultwarden
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:pyOTotNfAQkBTq4z4fFwEkPRF59lj2ejOjElgWBJAaNTdAuZSZB1MyU4YaEABilU8cRhZkQdMfOskwCabFQrDz0jmNpjZTKw+W3atT9byEn2jQjGdugY/B8kI4f/2lIaFT/CSAdM/eEWlK/RUs8gwCd9A3OcbMzfj5Fe+ZKutflYgcvEvqA=,iv:fGHnq2/+UNT4zvXxkDRy2SMKXacM8F32GSDNmC4Mh78=,tag:NVh/8kCjqUQiyDsW9jShTA==,type:str]
    SSO_CLIENT_SECRET: ENC[AES256_GCM,data:e9p2/KP2iOMWsbNMw49Im22CDIAHR7JCn9Jxry8CfXU=,iv:FZiDRH2mOMkti/f+RwpS0nRqsVViftNCZ1MUUQlLde0=,tag:0QRTybi27Dz03njRECJ6Zw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEwwcXJkcWVP
            K2E5MWs1WkUrRnlYUVh5NFJKM0NWeThBc28za1BEVzJuSWRPMHhMOVNiN0dxTzZv
            R2wyRkpQb1h5NlNOeHdDNE1SRUlpclVrVU1sdzVVWXFQQUNScUd4V3FCM2hrMFZK
            MHM4clYyTS9EeUU1ODNKSXZFZmhheElHdEI4SDR6S2krdzBPSmdCS2NhK1FVVSs2
            Nk5teUdoTTk1TTlZQWVUS1VaYVFFMjRCVVlqZVJ4aGpGZnFUQjFQOGJDaHAzZExG
            a0hUNDBpMW5RY0dxNUZOK3RSbHJsblhndE9HMVV2QVAzcGplTkNUZWJrU2pYb3p4
            Y3Fkd3FUTUt1NlkvWUk3bktGZVRSemFROWZGaUFoeXYwSTJ2bzRvbk1qT1gyUFFy
            aG9EQzZZc3dTUUI5bXdYSDJFTVlFTkhhRDcrdGZ5b0pvQWtCUnVBMjlBNlFpUFlq
            TWRHQ293RWRiNGhlaysrNWFzT2plVVJuTjVmeWMrKzM0bXRJVFNGT3cvUHZ6Y3R6
            WUNablEwaDF5amU2ZlhqL0FTMUEyamdQKytPMDBUUlM0VlFpL3N2cjJ3SFJjbmRK
            Q2dxWjY3OGxTdWVqc0haT1AwWi9IWFdxdGh5ek53VXZBeGRTKzdoU0lMN21DMXNv
            akhxdkoxSGlxRndWdVhZQVB3Y3p5c3FGR1dSZTdCK1BWOE04K1pxVzM4d3dBbGV3
            TWVqZ0RHL3NjaDUwY0Jhdm91aHcvRjFPNkhXbGFaOTJlcFJpcElEbUR3akhYOVBm
            ODd1d3NxalduRnlvemVidEJiSko1K3lYcy83MlZacGlGekdVbC9DekNmNnlDMFVq
            SkVTWW5zL3kxd3JRZHowQ3FRemd0VzNaSHptMXdPUVZQeWM1T2loV1MrQVpRSDVJ
            STdMdEJidGt6RGlBNWhFcnlscFNjTDc2TnlWUHZXREF0L3BQVEd0aU9sdGVOMTJy
            a3E0RDl4b0tING5zTWVubmx3aGVaTU9ueHhzREIxVjZGblBEbzRCeXRQekkybFJV
            aGJYZzNURXBoYkdFWVpRUXFnWEFwY25hNXpJTG1BaDFWV0V6cngwWEZYK3dOaXVy
            d3g0Zit6WVozYnc1MDQ0eXZ1b3lUeDc3MFFBSnBnQUxFck9hR3UrdkJnc3VCTlg4
            c21VOS9QQ1hQTDhRWUZGSjBIU0VlQS9MQkRGUFowSFNIemFlV0FrckNWSGRiK01Z
            aDQ2bXFydWJWakM1YnRyczIxbVlaRWsrTHlGQm15bzY2emRDb201THpQYVJsYko2
            TkdvaGV5U2pPVzhMQmlBcXNiUWkxRThyTWlHRG5oRWRxQnJkYlhNajkwTHZlRnB3
            TUZLZjh0TThDUHJBMmlDTTJ0NlVPbWp4Q1pkUDQrUG9JYk93b3dWOFdvOUNTZXJ3
            V2hJOUxaaG1HTG9INHJud09EZzVzWWR6bEhERnBFOGhVZ3N2ckpIdHo4MkhhcERZ
            THNacE10UUxUWTAwL2E2SFpNZmRja3RnVlFCS2lVR09wUGI1S09mZFZ6VEZkQWdh
            NXcvQzRYQ2dLRHphOW9WOTJqRzhQeCtab1BDN1NFR1Zab2M0cFFDK1NEN0NDdFFJ
            dkEyWmZicm1VYkZwQ3BKU3ZLdzBpUG95N3dMUHlwUXA2eG5vOFdzZFA2VFRwWWQ3
            alNubWsrTDJGcUdseHptRUJxNFdhMU0xYnZ4UmtOeUNzM0J2NTk1cWpQb2UycWgx
            WHFhWG84ZEZsQ2krMWxCRmFrVlIxSlZWaGlyZXZCNnZ2RmNON1JNRFNXSWErN1RS
            QzY1MkZEa3kzTU8zb2FEWGY3SWdCT0pVUmtvcHUzRlJwY1c5UVZLVVlhZlVabVln
            V3BjVGd6aGlhcmxOa2xIc1pZcUd5VHF6S1Fad3FVVElkMm5jNWowZkp3bjN2NDcx
            akRxY3M3ZlBaYmV2bVZnZk9mK2VBbWY3bTRFejNBbyszRWpMejdYM1hvdHNCQQoy
            amNLc1RPTTUvUXRsSVpHQ2x6NVBVaUpoOHp5c0VvSDdENW1idGZpOWRBCi0tLSBm
            eDVkT1VkdWQ4UEtNYzVud0VzU1lGOWhOQlg5RHI2blJsblhZdERuQlhvCkwCYBjP
            421bKHFt13wv7ltTBp1gXHZoJdzgUlMyzSoYwixu7Sc3p+E+CRUJ63ZlDPPScHus
            LNPvrpmBuFsqc+g=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1g5ye2kphr9ajqclgu5rerkr3crcjp57j83uj2qtn7xzmg922ky59d99ej2w8qhygeszx3xcyfadexup3c86mqqdf72m8vyyxqfy23cppqpfhdgdjapwy5s4susq27msrv9z8h9x499235x4alurymfmryd6qk5hxjwqgdk9gng2vs9sxck7gwpm98pu07ny2sf4saempd8eypj8nd9kyek9pj6ygq9vh5ar2vf069snj55peyjq8ndmnzj2rtpkf27mzfr9qc75rqseghgpzhfn2uarcqymxyyt8p5m9netzygdhmw3wfws0nsvgk804xs4jwjw2gmxwgkfnfq6gk7cmsree8jkklqsjs9r475epaps540jukeadhp2hkxesxvrv2mm3x7uh4wvhjyn90xyc9tppcczk2urtewpdrvelx8pwuj6x4fmj48zpnnsvajw3pprcw4uc40gcz9p0hdur0pgf4yr46gpsy3nzdjrdxk4dwzzhkfncvy6fvsr99fndnqdlz6uwu6qzqlk9cnm35dqd88ttjqvjc3qnm6m8axvu4md7dtmjtf7m35fawr52hqd9y7lhkarcv3775tqhu8mjdg26wd54h9tm8dy65cxpa2z2pvzq24gyrtxq262yx8qh36z8qkcf385l00nagz9yxekty3qrx57z92f6sk7ejwysyu2f03ek5z9vh5sc5kfhdyc9c7ad66spw4ztvag3f08nylrptawg8m9p48enhwduzyje2j5ngrpgkm2pre9k20t5pv08qe5pvezu2zamvky6c6qjcg7jt2qyelp0zqa94cxmw2pfqvpcjej9wdy0hdqgqeceq0dt8yyyk2gnzcx2npxr5nuy4rthzfdyvx7k55espctr4lny844c3pxx4xyrwkqkzfnr9ljtf6axwk63e0xtqec4en5437l425epv03fud36d3nmjuptr9fx96msynry77fzuqmhqhpr4marqef4wfa0lqdknpkfhrrce7x98h9aerjky52uuvrysxa68rzfrufspvpvcvfkstq2z2ytnwm2zw8jsefmufd0qwftqvdqmqcxpuqa0sk3jcfvnd60gzjnqfz8v4prkajx0wd95ann4xs3nhy6qyay5e40gdl9n7fsme5ks7n3srluqm9jrzraue2la3vknav4qr609245zc88xj6tnl2r4vv6knlag35v25tupa6gey33ru3hyg85k0auk7sfgsas9kj68q7qf0pld3kcquettueyc2p6kw52xdyzga3urvr8s5jptgq23ftphkvf024txw3ll6tuqsp6qnrrg6hvwdzp57jnjxyrtacvan3qe7e5q43z6qwml9yxp5fry0m4g8hhtpzjzvrensnw3ma5s9khppqsx9t8klyprap7mvcs87wg02sapvc4fprdg6wynejkd525hruncr895skvqetkaef3rlh957tpkw58zayfrxtyvgc63qqs47gmyatsvpyvfssam2wt7ra5k330kkml8xp8kpsqpwm6dg5h2jdagmz0hnrs5cyxrrvfq2f5dflk2m458tpq3nydkznsj4wcvpdh4p7em2xfmpv228acv9ns2lm6z8ducet9yatghjap562f2rj42wgqqcnncvzkyr2kn80n3hgas48pm22gvjql6u54ply830y8rr3eqfmwhztn4xa4uar80l96shs9wk9pt5uwscwfatxykqkqj2tnhqz0h4cc0ryesn6u02tdyx9hgvhjkvnlac42f4tmjs3vzzszsrx9p3m78cev4gfkn73krf0zfpttzap3xca9kwl2zezhd39dsa0u0ysy98jq5v329qh94lux6gpeqtz7y7cvk734475awtlkg3s3x2lyfgdphjd58p656385sa5u8qldjupgm2yy5pgqgfy8va2getdepq96xxdw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHc5dUNLdyBBcEtWUUxX
            cGtpR1lyc3N0SGJ5NUY1V28vWTFxVm0weXRFbGllWDE1Tm1xYgpaUXFOenNaaGlB
            cXRpcUZadkdBdVpPL05aMGtpUmFqanUyMUkxWFFIMzJvCi0tLSBVa3N6OXRkYlFV
            d0NEQVIvSy85bmlaajhUMVJSeWpQaXFLaVRaSGZ3eEl3ClXM/wLJJ4/9Ik1dnCpQ
            M0cOvNPtB+5aByjz2M8CUlA9mWIfU67Rgsxyh5ts+WhlcnJnozn8DhCEDCQs/zcS
            ffc=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2a8vlrsl9jm2zdzlhrxd7z7w7fg06rwtzf5pyhxdusps637qmeh7rphj3z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHNoQUYrUSBBNlNNRWdq
            TWF6ckFqWlFWYUNWRlhGTy8vM1BQTVRHbkp1bHhxVDNPLzQ3ZAp2Z0hqR211OU1a
            Znk3SnhoZVpKRW5zZGlNaUxyNFJ6RkorZDU1OVRSdUEwCi0tLSA4REVSc3kxaDc4
            OTU0SmdJU0ZSMkoxVitOT1lLSW9zV3IrRDU2K0JYeDhRCi0C28n2nCZhnTSI2n/H
            b1hivAdERvYS/1tSLCoo+DP3M1L8wWqBUjtskZmtOjDtXFm0EX8AlTo+2mOIhNBl
            G0A=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qdjws4vea067rq586qexcsz4k5eqmgh6mnsfld8uwy56dmkwrqhvwnt5e63
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGdNaEx1ZyBBb1NyZ1dz
            NDJ0YVRBb2tqNXhBVW0xN1FZVlFmaElKQVlqdjRpd0xWQnIwNwoxSmJzbmdmUjFT
            cVRKcUpseStZaTFVL1RsV05jMmlrdmdSOXZjMXNja1VrCi0tLSB6bTlYS0U1SHBJ
            alkyUis3L2MzMnJ6R2QzVFZQZ1YvdUYrZENZbEZ4V0xJCuinJ89nJFuBXbI9lc2v
            tO6i0P0an3+fnhByRLs51SPOHoRxYYouVxLVHVc2eP5b4z4fX7twFo4xhEB2cY23
            YfU=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qdprls2yh0zhxk3rm2ldtg7wt0sud6q3w9dftc9n9nxcyxkf3cvmz7ypm23
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGZwVlZXQSBBclM1alJa
            V3oyRXYxUU5RUWZQWXJFL0ZLYXhvelpVYVRuMUlYVXZYNHlzYwp3T1R4bXp5SEpG
            emJKbUllbTl4TW9yMkJrc0N3TC9EUjFjYVlwUFQwMVZrCi0tLSBGcGhCUm9mUFpC
            UUwvaGVyRlBjOWpXWi9HOUtSODc4cXFZZGdiRTIybSs4Cnkrgl7m5dTzly1yBT4P
            IYQ4xBnPAScrqwh0EKTHnzyF2z/qECU1K226RvOjMY+ZxFY5/+zvFmLpojrr2oxi
            c4c=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtpy5yqhhy3cvh8x48jx0dlge7uj6gmgwjp7m48zplr0uza87kdgy02f2rk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T13:34:39Z"
    mac: ENC[AES256_GCM,data:P/I4/NhSi2rC7s40zNuNwRMEU/Bxrv8v8osV4zT73rEmM1xhYTngD4FdccT2cuN+ZPqtOqyn5A1r/2fCy1JWYGi6DrI+yTqkRO1DXNx473NHVUKa9bhCI/GQyj6ZYS+kfxWsWql+J1omhWKXkc7rLRox3JblDmYweF+7dv/c0/Q=,iv:1GPefat7Ls1QQRQCaASONssrQIwt7hYEUeN7gOC+ch4=,tag:qT+lnmRAEQKtdfjzbIOo/A==,type:str]
    version: 3.13.3
