apiVersion: v1
kind: Secret
metadata:
    name: staging-deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9f2VDt3HvFNqAoZclUfNseQYeQ1OwJwgGk0NDBoTiZttnjNr8hRP1grt5OOqLPBy/KMUq2LG/yOzxW+JcNazTJew9oGuTMS4hUTd1p2aws+yUs5B/65XWHUkASfZL4ZRWzCeGMRX3JNN+vUBdLCsecifwsomZ9vk9nf/Qon6AE2vigPstM34pVM6HoaKJaVwMSynI72agQbveFWMohX97dIp1Rt/VknEQAHBegoFWnYL4mfKCYgJ2LGlMZw+rRVndaW2w0EfPFJb8zf8VzvqkEI+9sJk7PjuCzhI+A7+s3Iq17YeLEZZ6+CuAKjkUcn/zXgDlANBNCKeaisinmHyT1GrNCouhw+eLm0BMXqo0ZvOF3PZ+eS/HDpzkG0QhvQ2PmUT7AT4B0edZ6oUrsHYBit8OjrWcltYzr03pTNvlkQw6BEC43yJod4axhGarHb0VIodLEtxif79XG5/ZdEKhif6Rw4WBoagCxrjRyCLJO6ayRWkMXitqJvA7g/QK7XYg/hDjYUfED/bcS+BIc2yyVWZDAgBObLQSuzO,iv:ndj38ZkYqKPTijmg9kC/owwj+RPrvH6u9Vqj5Lf2gkg=,tag:YDiFsucUPTtoefbzj8Pplw==,type:str]
    identity.pub: ENC[AES256_GCM,data:KwCfnfVLYhkowNh0e7RflnLSfy7ohp3Ok5itCSZfrunRhKANmONiIeU2lAdOkOxcFvt46Qu3ef4EDcvYw0+QbC/UgVWAUAN7N23nSJtsrOHv,iv:I+zdQCjEszeaRoSxsQO34em4ELB148gbCQq3g6p8sxg=,tag:dbwQVmHS8WAlhxuIHp/XDg==,type:str]
    known_hosts: ENC[AES256_GCM,data:UUXBxZXaEQ/qIh19KR/8kykmS7wzLaAjERabnFy55gLn1noCY4wMPJCW7kI2SmPFFECyt/OuzXnUF3RelRczyxUcdeyq9m/tZNTwt2Mf1172iDuGPMVYNR294cEsaJRYj2BDwjkRUBLiMcWEjdmYM0xaZfEG7M0WINH9jS85hPUls2kO8i/6gTUT1PTrF9xb9uDyKSQpfslUz5Fr5QVPh9+wRh5OVSAWmkDs,iv:hsSyHMNsgOFAjN8vZF1N+CGeB0bRAOBMybFhtcjASlM=,tag:vWsBjPfPMoDDpDPBTU7v9w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEpOQzIwZ3JI
            S3IrYjkzQVpkdS9CQzZJNEtnU3RZcXRJWlhVclBualhSOHdOa0JPSW41QlUrcGRl
            NS91YmtXcy9BMTQ2QzA2ZXExZTJaU3lDelBKOFRDK2hLeGRGdVdlTTR0K1VOWVI5
            b25nYVFTUGU5OGJyZFJ3d0Fnd0I2Vm9FaXN5MytMeHNvbUlJcTRBMmMxRXZRcjZP
            Z05jQ1p1ZDdsbndya1pNQlRLMytVcU1xcmZhclJ2NmJqOHFINWxSbzRDVDh1bkR3
            WmQvWld0eTltWW1aV3hLaEQvOEtyR1lRTW5UUXBqVm5LY2E4aEVKY2RkVVdJdXhS
            SGZLWEtYeUZrS1VjSmNzdVNmOENwWFQrNHppZWtVcjNnRkZGdEZxd0k3czBzVWZu
            bnBMU2tYQmlxV2ZmbmZVeTBtNzRmOGcrSENHZ3U4OW1JcHcvaStYVXlKWUlLTlg3
            NWRRK3dBQ1hRVUdpK0J3YStyUnV5VGhTZlluTnp2T0tRM1JGVUw5U05PODBlWk9U
            akdYWHZpa1poSnJ0eHgyZ2RBdWtMNDE0cE5xTE1qTkc1NnNqSnFOQldjbVBYeFFT
            OGVEMlc5anFRSWJHMXFLQmprUnEzZGFaampjNG5QQ0wyb0NjcXBtMlpYUVVYUUtt
            RWVLUWs2M0d0b293Q0xuZGFCcGJUenF6MkhKRmxWVlBJekJDRHg2dzBjWkxMUXdh
            azBaWUtKdWZwdHYxaTB4ajg1MEkySGNsZW1TSTlaY29XemxkbUMwdE54TWVDZ2Uy
            U0MzQkFyK3lHdU53V2Z1MHZaWUFpTW1ZbGNQWUU0by82L3BQcDFMbFFyNEYvWGxv
            Ym1WUGZVNEIwZXhOZUJIWDJaYk9LcEozT0V6bkdvRnJxcUxGN0NyRVJDUWRLb3Z0
            Z2V4WUVzeWRjT1FJMmkyNEJObTNHZnJaa0RrZ0FyVVI3aisydFRQaW1rSFBrQkRD
            Vk10dEJkSHA5eldpd3VqRnpxMUVHTlFSOGJRWW1Hbm5tczdZNFE1RUt1TzdmcWIw
            RWpVSjlGRVYyd3ZoL2QvZlUrd3hrZEVWdDVTR3o4MENDUDNNRDB0dlNnWkV3QjM3
            UldIaTRxaVpvOEJyTjc0YnRsQkw0RkxFUTBLbXVzNmZMWTBXOHNOOWdKV0FEWWtI
            N3VzTXVXdXhTQXJUL05ZeGlYUXNSVTVxS283MlA0UWx6N3Q1K3k1ZnZsQ0FXSDdD
            eWhsVWdScVBNVW1ySW0vblRiSHlxK2F6aER4Z3lpRGM0MnNQYTFDS3NIaE4xcWt2
            ZUYvRlZ5R0YyYmNNd1R3cklIWnZ6Mk5CTXZoRVpSZW8vT3F1VENGbXdqd0pXWmJq
            ekluelFlVW1uU1NZdlhCY2orSTc5TnhHWlVod3BJQVdxdExkSHplREM3Vkg2NGY4
            cGFna3lkdjdZejk4SmVyUjZHMXVZcHl3RVJrNWpPTmdocG5OdGdzZjd3eC93MEE4
            cnJ5bGNQMGQzcGt3WE1JV0p0WE13a3JxUU1WNlh4eFF0SHN4b2N4anR6cEFsWjht
            MHNkTUZCbXo3WFZlSE81NVQraldCYndPdmxzWlVRaFZuQUFGdy8xRDZOeEY3Q0tV
            dUo0TnRuRFNwYkhXNmdQWDZiV0tHOEhua1l0VHBEdVhEV2xqSElHcTFlLzRURjdM
            QXB0cHZHUXppbzBOWk1VTWNldWxvQm1JcjhWVWthOFFpV2V2alhhckN1aDNSSGln
            YnFiRENnTWdhaHVGMFVsUFU1ZUhYUHhVS1FVYVZpdkpJTU9zZU56UmNsaEhTZlNT
            VFJRQjFNeUEzTUdjVTZ3cmswVWcwd281b2ZrUlBsVXlMamdzdzFXTnp4c0ttbll1
            R1RhYUpxanY2NURyNmM2UTVLeTVxRFZraUhzSGNyWDBETlA2Tm0vRTVLQ3FBNUJN
            eWJkSVI0OSsrb2pidWRjMlJXc3dsdHpqZVZ5YmxGcWZtK2c3RDdTSzNlQm1hZwpT
            UlB3b3M5dkJNSmFTNjFTWWZWY2xISk0rckRYd0x4cW5GVEp4OTFkNllFCi0tLSBz
            TXN6MGh6RVRRMnBQdjBlYnFPK0xlbWF5OTZZLzgxa3RZQXJvTWJzL2VVChPH2SNl
            Evtr6QoWaNAlKAv5c2PFOuXuG+umwMn3E0kEDtF/ea3vDejq/recPFHhsCeF/WYF
            RH+pSwNmiM920Vk=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq14n2zhq8npt7q2vc4csdplf5xfgse3uh2wdk7xpftsjdtafq373yfpnwe9j9w2lmj7uyy8smpy6nz3zz32yxthzx5d9prmp6zynuxhukngykkcma6gsnka7mtsm9j3xpfnz545tk3tv6cuu6ytesud0zgvlzvxmf2d8phh9pgmnvscvsznqwgcvw526r73y2vtjfv2a488um49ta4hfhtzq20cdu6ul4te6yjnw3eppc09ck2y3zrn2py9qk2jzasanynv398ykeylty53y0mg5ek2chp5fp3nk5k4juzqdp7jh8f55cz9jnf55ak0ujs9k76c4sxjd7tzfjqk69euklejehpkhmalzu5cgdz8jehqv9v2d8qqxphwxwwclzsthupmf6ec3gkd97ply44mxruvvj5rxe5kj94z7sktw2m4e5ypanndk3zy7j7ny8nhs56vzzpt4dtw72hxd4kt2ugxuw4c9u325eqcfett3dayhppu2pgnjpd9myjyevjeyjd0j8vg3yrdq7t8jzsk66j0crahfjj2xaaq2536cm2vgj4seq3yhfd0xs3mw40uwxvzfr2wll6vywxejcc64dvklnjce0qym7e83uv7xq34d5l7td5pegt6qfvvwxhve6n88yxmet83q4kr98h9jlp2np2kkzrsssgty5t9t37g5vqhvkdlynqs3styjxr23rc8zeqljcpdsp5fvz6uau53rque3dreyp404m5vggpw5gzfaku0zdnzgdykc9cgmuxdnwz4p9lxrsyqs55a3raehftlqa9vt9kcfdte9xd2pupc8fnla8mzatldrm7k6ua86d8sfp6p8spdsnj3w2zyk9nl4r4qm2c3mw440pxvqeztfucgkmslqsmxwnpxgehgd3pg8yfe47t5ynuk9syhd8ctx80tgx6z3mv7aqeq946xcmtn808wdnqzjscfq92y4x50r8f3fvjwy5tpppmdekrp6qmgagsvqzjdq2rrpny9atxw0t687ef29sqva9qqvdwqt4j5n7h4kmkxnrm2z4r5ce0g6ve7kc537jcew7wv7nzycvcu3jukyqqpn3pnp8gq2g40x3vdgj8ed7u2a6v92kgeskpgnxpzkmpzrnyr9d9ed7ghgar4wzmkrsk9flchxdev7wnsy5nz44c4x4cpszjpd6akyp5jstd89sr2an3dqmrn4lfv0fmfyegfeyegka4mrfjep755s3appj8wsgtu5sez2g5dtxcgllxasg8slq483eyev3hjpx33zqqpg9lud66j7zqa0sqxfn8v979d0q4gcz420cuvt9njksxkx96xvx0kq9sh9p5esg59lqnpwfxe2vz0jduuqqru00tv08m9te7mnp93fj69kp3ckptxvlms8k3q53lxk7rlg28hca6fphsrwk8nqteyqcwvq6hfxd59ascffec4j88rmpqg3fk5dpeh3e29s0j3qn9wd4j053gckq6fgs2njdmqeyd4wc0egat8sf6ccdsr383umyzmu6qgq3c04jk0npm25rahpk5cvzps8uh35gjs0dc20uyx98tfkemqapgezq4cgru3zq5yfkumvj7549xdts9xf3f5pqvznp5mv275p6ymprjtxhgtdpqy680c6xrtdfte3hx48j9cwq9f9quex4vwre8a5r30k8kznlac7th6czjyt646j4tqkuygud6wgxtg25mteyvt8n2kqq70x2e8gd53jjcyyz6lnxcjsqj2933x5dwufakuy96sdkmj6wdp9axs6zmdpxw9lycmas60xdert2zezg5g3f0wcgxyj8rj4e7dsnp8rys6n4f8nassdrlwg5eczr63tknr5vmut590y9yxahc5qewtdczwxwj3lz96kzzzk8fp8hew4v7xzxlqw4jtrxrh7fy0jyacd4gak8ryypydfk8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHc5dUNLdyBBcU9XTThL
            UVJTcUIrRis1MHBGWDJwYnNwc0xIOUVkNEdGaG1GWkJ1K0t1Nwozc0NxdVd4Q2pB
            Um9lQUFBcEZoNENkWTJOYjlWN1dQQTRXRUtGT3lMNUtjCi0tLSB2bHVsU0Z6TW51
            Y1JIQjVKd3A2eGhXWklabzdIKzBra3hMcmwwOFVEWjMwCm2fB3GpxUvt9aXZ1tWo
            DTOU0u0Ab6YlTrAlWhTiFxV/rLBvqfdrpcyRmkdyA2Ha7JpjRaAPYy7f7+Uji/EG
            2A4=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2a8vlrsl9jm2zdzlhrxd7z7w7fg06rwtzf5pyhxdusps637qmeh7rphj3z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHNoQUYrUSBBbWoreGhn
            WXVlRmVLUzBQVEJ4c2RYL0ZPKzV0TjBZOXRmTmFFUzhqWVRkbApNc29jdktOd0hF
            RFRHeWZWUktQZlpMbDNaSXE0eVA4V0wyVEFPdUFKUFdNCi0tLSBmR1JsM0t0cjhG
            NCtEY2RJY1NLMHNudXZvR2VHd0FzMHoyNXc3RmU3TFNJCrZfCwsKoCWDUI7IMoO9
            TDqENeNFvBQY1OTQ0vVkN5NtqBYNTd2BQ0iKn+u3MrxGOUIkTgy3687i769T5xYN
            X3E=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qdjws4vea067rq586qexcsz4k5eqmgh6mnsfld8uwy56dmkwrqhvwnt5e63
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGdNaEx1ZyBBOUFYdkwx
            RU43MGsvaUNCOUl2RlZLWkE4UGxXbUliYkY0V2ZCQWV4Y2RRTgpnb0grQkFGRVFi
            RVZxRVdrUUlWLzdWSmJwM2hFOEphTFl4ZkZneEVVZjhrCi0tLSAzODZzSnJkMzVt
            aWE1K3h4VGlaUm42MDF6QlhkYnBSTDQ4a3M2TGJROG1JCmuDF6Ba8fJAJjVLa4GT
            YwIzquqokkUnqlEhSSqdwNgnXuC+RDhfb3EcNEQ4xSwPay5LzjOa+qfy04h9Jg1f
            k4E=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qdprls2yh0zhxk3rm2ldtg7wt0sud6q3w9dftc9n9nxcyxkf3cvmz7ypm23
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGZwVlZXQSBBbHVOQ0ln
            K3lVdlkrc1dVNlhSejFjTUlDcUlQa2pxOTMzVk84em9aY1dFcAp3RWJ2dkJQelJi
            NmZjTyt3RWgxOTFwYm1MUGg2SlFSWThLZkdINWhGWDVBCi0tLSBKZGJJaGJTWTFp
            aXlTb05RQ3dSWDV5aXoxZXhmeTk4WEVqUUViTTY5MlowCsrTNz6dvcBezJduwTwK
            j0qMMpyEDfueJYI+4LYRb1jMNSy7gCxVeknhGQYiHZB/vkhfWfDZDZ4yylicog3R
            62A=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtpy5yqhhy3cvh8x48jx0dlge7uj6gmgwjp7m48zplr0uza87kdgy02f2rk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T03:40:08Z"
    mac: ENC[AES256_GCM,data:36B0xvhxdHFwa1YDHiqN8Fqf97/Y+RjHLby3zMPe6NsAKGyegUyYmrenjg0IY7RjxTUQbfQ1hb0Lv9AJQjYJZrqDAgqZTow5cTvvGl2Rkm4vx+oiwF2Ieuue/DvLEeOO1lVKCnFLC3bSwnsEczyFqGVlwGjmJaOWh2qzUgwLsu0=,iv:pOMx3mRUXL8/x2On0VqLgTQPJI2ixNPPQ3YVUxd163c=,tag:W9n2ixcHpYSBdYywRjscOQ==,type:str]
    version: 3.13.3
