apiVersion: v1
kind: Secret
metadata:
    name: staging-deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9f2VDt3HvFNqAoZclUfNseQYeQ1OwJwgGk0NDBoTiZttnjNr8hRP1grt5OOqLPBy/KMUq2LG/yOzxW+JcNazTJew9oGuTMS4hUTd1p2aws+yUs5B/65XWHUkASfZL4ZRWzCeGMRX3JNN+vUBdLCsecifwsomZ9vk9nf/Qon6AE2vigPstM34pVM6HoaKJaVwMSynI72agQbveFWMohX97dIp1Rt/VknEQAHBegoFWnYL4mfKCYgJ2LGlMZw+rRVndaW2w0EfPFJb8zf8VzvqkEI+9sJk7PjuCzhI+A7+s3Iq17YeLEZZ6+CuAKjkUcn/zXgDlANBNCKeaisinmHyT1GrNCouhw+eLm0BMXqo0ZvOF3PZ+eS/HDpzkG0QhvQ2PmUT7AT4B0edZ6oUrsHYBit8OjrWcltYzr03pTNvlkQw6BEC43yJod4axhGarHb0VIodLEtxif79XG5/ZdEKhif6Rw4WBoagCxrjRyCLJO6ayRWkMXitqJvA7g/QK7XYg/hDjYUfED/bcS+BIc2yyVWZDAgBObLQSuzO,iv:ndj38ZkYqKPTijmg9kC/owwj+RPrvH6u9Vqj5Lf2gkg=,tag:YDiFsucUPTtoefbzj8Pplw==,type:str]
    identity.pub: ENC[AES256_GCM,data:KwCfnfVLYhkowNh0e7RflnLSfy7ohp3Ok5itCSZfrunRhKANmONiIeU2lAdOkOxcFvt46Qu3ef4EDcvYw0+QbC/UgVWAUAN7N23nSJtsrOHv,iv:I+zdQCjEszeaRoSxsQO34em4ELB148gbCQq3g6p8sxg=,tag:dbwQVmHS8WAlhxuIHp/XDg==,type:str]
    known_hosts: ENC[AES256_GCM,data:UUXBxZXaEQ/qIh19KR/8kykmS7wzLaAjERabnFy55gLn1noCY4wMPJCW7kI2SmPFFECyt/OuzXnUF3RelRczyxUcdeyq9m/tZNTwt2Mf1172iDuGPMVYNR294cEsaJRYj2BDwjkRUBLiMcWEjdmYM0xaZfEG7M0WINH9jS85hPUls2kO8i/6gTUT1PTrF9xb9uDyKSQpfslUz5Fr5QVPh9+wRh5OVSAWmkDs,iv:hsSyHMNsgOFAjN8vZF1N+CGeB0bRAOBMybFhtcjASlM=,tag:vWsBjPfPMoDDpDPBTU7v9w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IG1hNk1kemRu
            b2pNb2RoWXFnQzhMZW5RUkZYNnJZUDZIeXBweUhsSFBmMkpiUk5keDdBbmR0MmJq
            QmRWYUdCWWtodWdDWkxRR2VYaEltclk5NUJpeEZsdllvcVErc0lvVGtnZ1BlelRx
            U2xlZXlEZnAxTldCSDBzaGVKWjkzRHVKQlVIVzFpUy9jV1VnelFJOGJUVG1jNlVB
            b2hmckZJdWtIalk4NmRrdTBxNnNGVUVpOFhlaHhuSzN3Mmhsb1g2WkFEMWd6UUdJ
            NmdJTlBicG41NVRqQWxrL2xhODIyRWZZVTlNK3p5SnQ4c0pVL2VlaHpCZ2UwbVln
            VXR3T2VFWWhIdFpVT1VHT3NqdVJReElYeStUNGdzTzE5SnZPeWdRSU5wWE9Mc215
            QXZpTExpa3c3a1Z5dUhVZjduMGlIYWovbkZhbHpZNmdXLzRBSWt1S0x5RTJpOXVJ
            RGZMWTVYUXlnNmlmaUh4WkNRRitHWko3aW9BZDFUYjRGMTZZajVMK01Eb0dpMFJQ
            R29Ra3R4Y0xUWDFrcVJGWFhRcEpmb3N3eHQwN1ZKamwvdEdLZGNPWTh0QU90TjNN
            L3lJUS9qNGg4a1Z0aXNZemZRakMzWEsrM28wM25ZcGVKcFNpTDZHcVkvN0RnMnpq
            RFNiNURQajl4RjFONjh0S1BBc3RRdE5LSURRVlVVeGc2dGZNV2prWUhHeFNvUW1m
            TE5xMnUvb2E1a2hEVmJhMGR5SnRGdExRMGVRbEM5RHJFdGs0QlRsWTNQSlhnR3pZ
            RlZJSTUxTUg5S1p3clozdzI2NlMyT1BBWVkyanBLT1R4aXFYN2lQOUYra09EUTZ4
            Q25RWHpMSTJZSzMydGFGNVAvRmN6QTU2QUhHRUdCU2dEWVl1K1JHVEdvMlQvMXhJ
            TlpOc1luQWpMZ0hTRVV5ZjdWY2tsY2E1RkpwTnJJbDlLUFdLLzhsUmowTTIwSmhj
            UnFKQktvazV4Sjc2dVljbDZVM2VwTnpzMHh4YVAvdWw1OGl0WkQxWVhLbmRBYU9T
            OWZmbHREbUliZHZJZTg3ZU9lRDROSTBpeFpEWkptUzgzUDBHMTJoazFsS1hrenRN
            Y2RHdUpGN21KeS91M1lqVXJUMmdPMjNGcUhvNGZTQXArTmhEalBPQUFHTmJNQi8w
            c0Q3TTdScHlkMFVScExxZ2NJN3pjeDhyYXdIem84RGRRbXljV1o0akZuZ1lZL2Ez
            RExENGRXR3dnamVaMk15MXZLVzNSZ1gvWHdsUHNnT0FGWW81Y2hxdCs2UmJUVTRN
            bHNSL2JncENGZHBML0lVSmxrNnY4SzN3Y2RDUkNzNGloVFFjMlE2ZkZZVW5jMUdp
            Q1JwZ1N4am13TG1FblZQVFNPSWRoeVc1MFRBVERjL0pHbVowT2NDTExrWTNSb2hZ
            c09HU2NRWUJjTUZocmozSG8zRGU3bVNxbUpzNENzZjgrSGV2MENCb0xoVWI4R0lI
            elU2emllUVh0Rk1yK3haNVhhSzZFWFl0dlY4bGJYd3dRVWV6Um9hVE0wcStYaFBi
            cEg1MkdDY2dpZGZOU1dTaGtBUnRYMnRVSFpBWEIzS3pTOUNYakw3NFoyUEZHbDVW
            cTh5dzlONm1rN1RrNDJjRFhtRll5TG14cElaNnNScUNGUThJT0hDMHJKM3lWT1gz
            S2JzemFjQllJMkdZajIyTXV3ODE5S1h1dER4LzA0NjRZMGUyVEVma2QvUEJPMUsy
            QkFqU1NMK2ZVT2JSazRqTHdHNmRIUE1ib2RwTlo1N1pQRXVlY2MvMHpQbG1aSlJ4
            UFRQUHFTamk2UkZMY0hhQ21CcnpXTHVyUU5qaEJCR0JQUVg1Z09SM3JBQjFQZlph
            KytZQkQ2NmZ2bmMycVRvNG9MNnRXUWUySmtMajUya1JCZ3h5TENiT3ZIbE5xZGVL
            amxZMGVxekpuVmpkQk96bEJwNmszRVFFQldUSVZ4L2hILzNxb2E2ajMzaE1MZwpJ
            aW5CR2prTlV2U0UzSDF4cGMxT2pIWGozekluNSs3clpzVlV4WXZjRUpJCi0tLSBs
            YXcvbnc3VkJKVFhpVlZFNzBKNEY2WFhKOXFoUy8rdmhRODlycm02dEFJCrPGd6qY
            BBxIyn1ngUAocEgd0hwDCbjjTuFK6P8GWXu3GdAeXMWgW59s7qMpw02JR+zZgDhQ
            q6qaTJmw36tlG4I=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq14n2zhq8npt7q2vc4csdplf5xfgse3uh2wdk7xpftsjdtafq373yfpnwe9j9w2lmj7uyy8smpy6nz3zz32yxthzx5d9prmp6zynuxhukngykkcma6gsnka7mtsm9j3xpfnz545tk3tv6cuu6ytesud0zgvlzvxmf2d8phh9pgmnvscvsznqwgcvw526r73y2vtjfv2a488um49ta4hfhtzq20cdu6ul4te6yjnw3eppc09ck2y3zrn2py9qk2jzasanynv398ykeylty53y0mg5ek2chp5fp3nk5k4juzqdp7jh8f55cz9jnf55ak0ujs9k76c4sxjd7tzfjqk69euklejehpkhmalzu5cgdz8jehqv9v2d8qqxphwxwwclzsthupmf6ec3gkd97ply44mxruvvj5rxe5kj94z7sktw2m4e5ypanndk3zy7j7ny8nhs56vzzpt4dtw72hxd4kt2ugxuw4c9u325eqcfett3dayhppu2pgnjpd9myjyevjeyjd0j8vg3yrdq7t8jzsk66j0crahfjj2xaaq2536cm2vgj4seq3yhfd0xs3mw40uwxvzfr2wll6vywxejcc64dvklnjce0qym7e83uv7xq34d5l7td5pegt6qfvvwxhve6n88yxmet83q4kr98h9jlp2np2kkzrsssgty5t9t37g5vqhvkdlynqs3styjxr23rc8zeqljcpdsp5fvz6uau53rque3dreyp404m5vggpw5gzfaku0zdnzgdykc9cgmuxdnwz4p9lxrsyqs55a3raehftlqa9vt9kcfdte9xd2pupc8fnla8mzatldrm7k6ua86d8sfp6p8spdsnj3w2zyk9nl4r4qm2c3mw440pxvqeztfucgkmslqsmxwnpxgehgd3pg8yfe47t5ynuk9syhd8ctx80tgx6z3mv7aqeq946xcmtn808wdnqzjscfq92y4x50r8f3fvjwy5tpppmdekrp6qmgagsvqzjdq2rrpny9atxw0t687ef29sqva9qqvdwqt4j5n7h4kmkxnrm2z4r5ce0g6ve7kc537jcew7wv7nzycvcu3jukyqqpn3pnp8gq2g40x3vdgj8ed7u2a6v92kgeskpgnxpzkmpzrnyr9d9ed7ghgar4wzmkrsk9flchxdev7wnsy5nz44c4x4cpszjpd6akyp5jstd89sr2an3dqmrn4lfv0fmfyegfeyegka4mrfjep755s3appj8wsgtu5sez2g5dtxcgllxasg8slq483eyev3hjpx33zqqpg9lud66j7zqa0sqxfn8v979d0q4gcz420cuvt9njksxkx96xvx0kq9sh9p5esg59lqnpwfxe2vz0jduuqqru00tv08m9te7mnp93fj69kp3ckptxvlms8k3q53lxk7rlg28hca6fphsrwk8nqteyqcwvq6hfxd59ascffec4j88rmpqg3fk5dpeh3e29s0j3qn9wd4j053gckq6fgs2njdmqeyd4wc0egat8sf6ccdsr383umyzmu6qgq3c04jk0npm25rahpk5cvzps8uh35gjs0dc20uyx98tfkemqapgezq4cgru3zq5yfkumvj7549xdts9xf3f5pqvznp5mv275p6ymprjtxhgtdpqy680c6xrtdfte3hx48j9cwq9f9quex4vwre8a5r30k8kznlac7th6czjyt646j4tqkuygud6wgxtg25mteyvt8n2kqq70x2e8gd53jjcyyz6lnxcjsqj2933x5dwufakuy96sdkmj6wdp9axs6zmdpxw9lycmas60xdert2zezg5g3f0wcgxyj8rj4e7dsnp8rys6n4f8nassdrlwg5eczr63tknr5vmut590y9yxahc5qewtdczwxwj3lz96kzzzk8fp8hew4v7xzxlqw4jtrxrh7fy0jyacd4gak8ryypydfk8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHc5dUNLdyBBNnYwejVL
            QVlMUTNEUEVwUnN2SnBiVzFKQUhWRGZOdzY2Z211MldvR1B5VAppT2F5VVR5VDcy
            MDJTN0drT1RKa0p1Z0pxRlV3U2xJV1lsQ1FUYmVqL2pZCi0tLSBqME5rWWVzWG9s
            dlZ6c3pTM0NmLzhIMXFET3d3MGllS1d3dk00ZHptQzl3CiOuoWmzZRuhzGjHLAM1
            hS4prfCkBZ5kSmC/eNTnS8NYlgWqEwNH60K4YxGmzs+/6/C2/4TZhAhCkPZ2cAws
            a+I=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2a8vlrsl9jm2zdzlhrxd7z7w7fg06rwtzf5pyhxdusps637qmeh7rphj3z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHNoQUYrUSBBNHpNc0kw
            cUJRYm5SQ1QyeG1hN3JSV3VFYUlzUnVFNkxYV0ovTUtwdk9IMgo2RUV2K21nY1Fi
            MlQwaHlWZEs4akdUTDM5Q0V1UnJkNE1hN2xhSXRaUCtnCi0tLSB5UVYxTUNhaVFY
            UEx6V3liTUIvT3E4MmF5dHY0YVB5MmpMc0hhWXhQRFd3Cr9Wr1oBxY59GTSa58Mn
            TT3aKMu+zEofRGBCe695ULNycdpn4JHPc8eFK4rqfs0+zydoUzkf5oEu6pwmBrRt
            i8w=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qdjws4vea067rq586qexcsz4k5eqmgh6mnsfld8uwy56dmkwrqhvwnt5e63
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T03:40:08Z"
    mac: ENC[AES256_GCM,data:36B0xvhxdHFwa1YDHiqN8Fqf97/Y+RjHLby3zMPe6NsAKGyegUyYmrenjg0IY7RjxTUQbfQ1hb0Lv9AJQjYJZrqDAgqZTow5cTvvGl2Rkm4vx+oiwF2Ieuue/DvLEeOO1lVKCnFLC3bSwnsEczyFqGVlwGjmJaOWh2qzUgwLsu0=,iv:pOMx3mRUXL8/x2On0VqLgTQPJI2ixNPPQ3YVUxd163c=,tag:W9n2ixcHpYSBdYywRjscOQ==,type:str]
    version: 3.13.3
