apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: overrides
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/infra/overrides/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
