apiVersion: v1
kind: Namespace
metadata:
  name: openbao
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openbao
  namespace: openbao
spec:
  interval: 15m0s
  url: https://openbao.github.io/openbao-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openbao
  namespace: openbao
spec:
  interval: 15m0s
  timeout: 5m0s
  chart:
    spec:
      chart: openbao
      version: '0.29.4'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openbao
  releaseName: openbao
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  valuesFrom:
    - kind: ConfigMap
      name: openbao-values
 
