apiVersion: v1
kind: Secret
metadata:
    name: prometheus-secret
    namespace: labmap2
stringData:
    PROMETHEUS_PASSWORD: ENC[AES256_GCM,data:n9VGyTlOiFgqJayAEVhv,iv:rKgV9HBzSB9mHmKn9FGLAsPxg65QGo0jfmOigLPvWT8=,tag:A3ie9sEZ+ezdXgPzovB3ZA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHZDK2UrdjYw
            bUpsT2k2WTdBV1hNeHJNektlZ25wTWZmMGJGMDBRQjZQU2xPcm8rMU9IbEc2R015
            L1Q5SDFDMXBzUjlvdDhjcXJKNUJ0bXZFZC81WkdIMzFrTWQ3citvTXRQdFl0b1gy
            QUlFNUQreEw4RFNqS0hMS1RrK0hWd1RLMnZMdzZLSkhiNGRNUUxJbkR0MTBISFdz
            UGRSR2dmUjJIZWF6dE9vZDVwWCtLUTJtQ2V2bWZYNTJWY3lhQyt2YXN0QWt3ZSth
            VUZhNlM2S29VUmRyYlJ4WDRtYmJGVG5NWmwraWI2Nm4ydS96enB6N25WdkNuKzJK
            YW5WU2FmTGpxQVVKMHNVWWZxOTc0UzdiQkhXbldCeWNnTFY1OTN1OVkveUxtTzNr
            Y2dSUkZ3TmJDR0FzS2MzZDh2VzVsQ01lYS80RnMrb25KOUtRZHprQjBhem1EV3k5
            dXVCeisyRjZLanQ3TzRLem9mMDllMk9Gem4vSXRkT25XeFpWS3JFdzVMVFlEZHRG
            Y3VtbklNNWF5OCtrZGt2S0hyV1NLVGkwdTd2Wk1VMGcvRVNwL0d1RmpHL0RHL3pT
            SUtFd2IxRk04K1pPbjdGb2Qxc2xDSTRNYmRPQVduSTFwb2NJZXFyaTVORjZwTVBy
            OGl6SnRWaVpkQURIc3ZIa05JT0o2ZG9PVFk1TUE4VEQ4bEV6eEltNkdNK2pFV3d1
            RXlWOU44amQ5RWxTNHhJb244ekpVQXNHN096R0syNy9QQ21ybXBONWs5VTVKbXY0
            MGl4TmNvSGZoUVU2d0dDZmZud3ZQV3NJc01mYktlN0xJWk11OWFJVmppOEhyTldJ
            Q04vcm1RcUJxMFVTSE1PckxOSGJrUzVnelJ0bVNKNGgwMUF6SndBbzZZcnBncW5a
            NnFFQkRrRGNFYUMxY05PY0JWMlNGOVN3VnR6c1p2ZjV2WU5UQVVLYUhwb1I5elIw
            MjZRWWFxa3FhSXg4aG5PQlQ2SGg1RFdVQ0xMREl1d0k3RXRmZnBjUTZRak9YNDdr
            RWVqamJsNi9aVnM2R3ZqeE1GaTJVTzBnekV3TXkvMThueUdkZkloRk9aTEFWS0F3
            NXdUUE9jajQ4ckptYnIzVS9QV25HckdETUJrdkRSbUhRLzh1aWxOcy9QelIxVm5I
            RHVNUnpiWjdTVGJnbWJSWjVUdzBCd3dGejFsd1JFTXh6bE5POHVlU3EzV0RGSU4r
            OEYxaldJL21Ua0ppdW9nUENmQ1M1ZGhsT2p5ZlNpblBtamd3UHdDRVVRQUJJaWtv
            TFB4WkQzMVYzTXRGNzk2bUhUZ2tsL3oyUHNUSjZzaTNLWStJb2c3SDZCM1J0SzhH
            NHZXVEFKMkhLbXpuZkdBYWlpZnkrNWJIWEFLcXlsektrL2tTMzRtbDMzSWlNMUk0
            cW41cUVWcUlZRVVTZ2lGbGVRcm5XOGtEU1daMXVseHJVZ2RiT0F4YmcvTXdOcmdu
            Z3ZFY3Q2TE9qd2VQbzBSc2J4OUR5Sld3NXBZRVM2NWRweTVXQVlsOFNWTXBZdGU2
            WTVzUWd0Wk00cGxSa3lvYjAvdmswOEloQXBranBRUXZXMmtVVXo1ZDJiNUtaSCtw
            TSt4NlYrK0RZelE3WkdBMnB0S3VPdEY2bHk3bHVSNmhxMDZBTmw4OG9ZNEE2ZjhF
            ZThsT0hKRFlvd2t5Vm5naitPTzl1VzZEUnhraHR6dkNrMFFYUXdpYm1NZmRMbEpS
            THVnYVNKT3lrSC93cUdQUDZNaFl1MnJjTG5wUFhzWUZMZmU3WS9pUzFhdStaYzR3
            ZmowRENQc09iVlUrcU5GeTlXN0wwV0h4WnpMVm9lVk1qSWNBV0U0djNEUE85VlRo
            R1FZaTZ3d0o4Nk5odzNBdDFLYjVXc2g0VE9rMndVMEwzYnlqeGdGcE1KbXo3UFd0
            UHRZOUFOR2V3S3FDbWQ4SS9Ddk0wS0IwWHd6UzJ5NGlHVnZRMkVRQ0QxYURaZwov
            WW4yT1gwV05Lc1Z6L2h4SjZMalAwelI1dUJPUnN4bTZSaGNOR1F3dW84Ci0tLSBy
            UEhITHhGSWJ6YjkzUFBZc2RVQXlKUnR2MjRYeVBpOHI5YVJvY2FlLzlVCi7bXnIb
            Whe50Sr9wM94mVBQ33w7kyQOcQkcQgWbsXYt7eQU1asSrPwpZsPmbCq6CsMcJOEe
            yFn0Q0FlOUMZfWM=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1g5ye2kphr9ajqclgu5rerkr3crcjp57j83uj2qtn7xzmg922ky59d99ej2w8qhygeszx3xcyfadexup3c86mqqdf72m8vyyxqfy23cppqpfhdgdjapwy5s4susq27msrv9z8h9x499235x4alurymfmryd6qk5hxjwqgdk9gng2vs9sxck7gwpm98pu07ny2sf4saempd8eypj8nd9kyek9pj6ygq9vh5ar2vf069snj55peyjq8ndmnzj2rtpkf27mzfr9qc75rqseghgpzhfn2uarcqymxyyt8p5m9netzygdhmw3wfws0nsvgk804xs4jwjw2gmxwgkfnfq6gk7cmsree8jkklqsjs9r475epaps540jukeadhp2hkxesxvrv2mm3x7uh4wvhjyn90xyc9tppcczk2urtewpdrvelx8pwuj6x4fmj48zpnnsvajw3pprcw4uc40gcz9p0hdur0pgf4yr46gpsy3nzdjrdxk4dwzzhkfncvy6fvsr99fndnqdlz6uwu6qzqlk9cnm35dqd88ttjqvjc3qnm6m8axvu4md7dtmjtf7m35fawr52hqd9y7lhkarcv3775tqhu8mjdg26wd54h9tm8dy65cxpa2z2pvzq24gyrtxq262yx8qh36z8qkcf385l00nagz9yxekty3qrx57z92f6sk7ejwysyu2f03ek5z9vh5sc5kfhdyc9c7ad66spw4ztvag3f08nylrptawg8m9p48enhwduzyje2j5ngrpgkm2pre9k20t5pv08qe5pvezu2zamvky6c6qjcg7jt2qyelp0zqa94cxmw2pfqvpcjej9wdy0hdqgqeceq0dt8yyyk2gnzcx2npxr5nuy4rthzfdyvx7k55espctr4lny844c3pxx4xyrwkqkzfnr9ljtf6axwk63e0xtqec4en5437l425epv03fud36d3nmjuptr9fx96msynry77fzuqmhqhpr4marqef4wfa0lqdknpkfhrrce7x98h9aerjky52uuvrysxa68rzfrufspvpvcvfkstq2z2ytnwm2zw8jsefmufd0qwftqvdqmqcxpuqa0sk3jcfvnd60gzjnqfz8v4prkajx0wd95ann4xs3nhy6qyay5e40gdl9n7fsme5ks7n3srluqm9jrzraue2la3vknav4qr609245zc88xj6tnl2r4vv6knlag35v25tupa6gey33ru3hyg85k0auk7sfgsas9kj68q7qf0pld3kcquettueyc2p6kw52xdyzga3urvr8s5jptgq23ftphkvf024txw3ll6tuqsp6qnrrg6hvwdzp57jnjxyrtacvan3qe7e5q43z6qwml9yxp5fry0m4g8hhtpzjzvrensnw3ma5s9khppqsx9t8klyprap7mvcs87wg02sapvc4fprdg6wynejkd525hruncr895skvqetkaef3rlh957tpkw58zayfrxtyvgc63qqs47gmyatsvpyvfssam2wt7ra5k330kkml8xp8kpsqpwm6dg5h2jdagmz0hnrs5cyxrrvfq2f5dflk2m458tpq3nydkznsj4wcvpdh4p7em2xfmpv228acv9ns2lm6z8ducet9yatghjap562f2rj42wgqqcnncvzkyr2kn80n3hgas48pm22gvjql6u54ply830y8rr3eqfmwhztn4xa4uar80l96shs9wk9pt5uwscwfatxykqkqj2tnhqz0h4cc0ryesn6u02tdyx9hgvhjkvnlac42f4tmjs3vzzszsrx9p3m78cev4gfkn73krf0zfpttzap3xca9kwl2zezhd39dsa0u0ysy98jq5v329qh94lux6gpeqtz7y7cvk734475awtlkg3s3x2lyfgdphjd58p656385sa5u8qldjupgm2yy5pgqgfy8va2getdepq96xxdw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHc5dUNLdyBBNXErN1dV
            MTZDU1V3U0hjNVd2Wm5SWHZLY1hRZlRtbnpvUk1ISlB1SGhVRwphYnhUUlBSdGd3
            T1VFdk5NYlpJL1VDRXNBWVoxTWV4RGwzcmlLM0FJUEQwCi0tLSBCRU9BbUd6TUU3
            MXBaclBBckVmcjRqdGR6VTBieU1IanRjbEIzTDV4TEhrCtIbKzTjnQyn8U2BU96S
            EQHB1JQvZYV+1NIpuH0CPLAht8jme62KLiGB4TIuURvZUyM7E1uR/2BKYRC4+co6
            BTk=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2a8vlrsl9jm2zdzlhrxd7z7w7fg06rwtzf5pyhxdusps637qmeh7rphj3z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHNoQUYrUSBBMUQ3NGpM
            cDdlb0RvZW5haDk5aWE0Mk1xU1VyalJXSWdEdnQ5QzFldk01ZQpuRWFLa085SE01
            MHpqU1ZrUDFkRkpUMTJZQktoRmQ0QnVqU0gvZXNBdTcwCi0tLSBrOTZZWW9nMEZt
            WjZRM2cvSkVvZkJjZlR5OU9mVlltaWxKN1ZqL01WUkFzClVW9dKDvh17O2MR3WRe
            EZ6YW8EcLD15L7eUNMWM49VPc7UC6wikaHuYEGknk49rq3pPVMyEQrBEcx9BxsWX
            lsM=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qdjws4vea067rq586qexcsz4k5eqmgh6mnsfld8uwy56dmkwrqhvwnt5e63
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T14:14:04Z"
    mac: ENC[AES256_GCM,data:/ZogD4apdzCt4yLSdYVbeUr+8cfG7/59GN7ERrUfPcmbLg0eRKPrUDU33E+k7lL0lm258FbPNru5zWhCYtEMOLVqgdMGCjepxdVYi2GvqMPMys0fJn7ypl7dMsg7fxKP4jxCrgZjZWwXfgOW4GT0IiHK8Unt5fqyeZLIDDRJpZs=,iv:ddXOw+MT2BvJ362LqwJYHK/RlCNaTG9a0fYYeC6CaMM=,tag:ND3rQ8PlPlp9Ecy76vdw1Q==,type:str]
    version: 3.13.3
